# Generated by Django 2.1.1 on 2018-10-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='cpf_text',
            new_name='question_text',
        ),
    ]
